version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: pinboard-server
    container_name: pinboard-server
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: pinboard-client
    container_name: pinboard-client
    depends_on:
      - server
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    web-root:
      driver: local
